name: Deploy Docker

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_SECRET_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan 83.166.234.234 >> ~/.ssh/known_hosts

    - name: Create .env files
      run: |
        ssh -i ~/.ssh/id_rsa ubuntu@83.166.234.234 "mkdir -p /home/ubuntu/hw_6_back/lab4/auth && echo '${{ secrets.AUTH_ENV }}' > /home/ubuntu/hw_6_back/lab4/auth/.env"
        ssh -i ~/.ssh/id_rsa ubuntu@83.166.234.234 "mkdir -p /home/ubuntu/hw_6_back/lab4/market && echo '${{ secrets.MARKET_ENV }}' > /home/ubuntu/hw_6_back/lab4/market/.env"

    - name: Deploy
      run: |
        ssh -i ~/.ssh/id_rsa ubuntu@83.166.234.234 "cd /home/ubuntu/hw_6_back/lab4 && git pull origin main && sudo docker-compose up --build -d"
